name = "r2-cache-proxy"
main = "src/index.js"
compatibility_date = "2025-06-01"

[[r2_buckets]]
bucket_name = "burning-dezibelz"
binding = "burning_dezibelz"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "burning-dezibelz"